// Build the hosted-deploy bundle: stages the client into dist/deploy/ and
// generates a single-file Durable Object server (dist/deploy/server.js) from
// the shared sim modules + server/match.js. Zero dependencies; run with:
//   node tools/build-deploy.mjs
// Output: dist/deploy/ (zip its CONTENTS so index.html/server.js sit at root).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'dist', 'deploy');

// Modules inlined into the server bundle, in dependency order, with the names
// the later code needs in scope.
const MODULES = [
  { file: 'src/config.js', names: ['PALETTE', 'CLOTHING', 'SKIN', 'HAIR', 'TUNING', 'MISSIONS', 'ACTIONS', 'I18N'] },
  { file: 'src/rng.js', names: ['makeRng'] },
  { file: 'src/world.js', names: ['createWorld'] },
  { file: 'src/characters.js', names: ['makeAppearance', 'makeNpc', 'makeFaker', 'updateNpc', 'scheduleResume', 'updateFakerAI', 'integrate', 'separate'] },
  { file: 'src/lights.js', names: ['LightCycle'] },
  { file: 'server/match.js', names: ['rooms', 'makePlayer', 'handleMessage'] },
];

function inline(file, names) {
  let code = fs.readFileSync(path.join(ROOT, file), 'utf8');
  code = code.replace(/^import[^;]*;\s*$/gm, '');            // strip imports
  code = code.replace(/^export\s+(const|let|function|class)/gm, '$1'); // strip export kw
  const tag = '__' + path.basename(file, '.js');
  return `// ---- inlined: ${file} ----\nconst ${tag} = (() => {\n${code}\nreturn { ${names.join(', ')} };\n})();\nconst { ${names.join(', ')} } = ${tag};\n`;
}

const bundled = MODULES.map((m) => inline(m.file, m.names)).join('\n');

const server = `// Freeze Faker hosted multiplayer server (generated by tools/build-deploy.mjs
// — edit the sources, not this file). One Durable Object instance handles all
// rooms internally at <base>/ws.
import { DurableObject } from 'cloudflare:workers';

${bundled}

export class GameServer extends DurableObject {
  fetch(request) {
    if (request.headers.get('Upgrade') === 'websocket') {
      const pair = new WebSocketPair();
      const client = pair[0], ws = pair[1];
      ws.accept();
      const conn = { send: (s) => { try { ws.send(s); } catch { /* gone */ } } };
      const player = makePlayer(conn);
      ws.addEventListener('message', (e) => {
        let m; try { m = JSON.parse(e.data); } catch { return; }
        try { handleMessage(player, m); } catch (err) { console.error(err); }
      });
      const bye = () => { if (player.room) { player.room.remove(player.id); player.room = null; } };
      ws.addEventListener('close', bye);
      ws.addEventListener('error', bye);
      return new Response(null, { status: 101, webSocket: client });
    }
    return new Response('freeze-faker ok', { status: 200 });
  }
}
`;

// ---- stage the client ----
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(path.join(OUT, 'src'), { recursive: true });
fs.mkdirSync(path.join(OUT, 'assets'), { recursive: true });

for (const f of fs.readdirSync(path.join(ROOT, 'src'))) {
  if (f.endsWith('.js')) fs.copyFileSync(path.join(ROOT, 'src', f), path.join(OUT, 'src', f));
}
if (fs.existsSync(path.join(ROOT, 'assets'))) {
  for (const f of fs.readdirSync(path.join(ROOT, 'assets'))) {
    fs.copyFileSync(path.join(ROOT, 'assets', f), path.join(OUT, 'assets', f));
  }
}
fs.copyFileSync(path.join(ROOT, 'index.html'), path.join(OUT, 'index.html'));
fs.copyFileSync(path.join(ROOT, 'styles.css'), path.join(OUT, 'styles.css'));
fs.writeFileSync(path.join(OUT, 'server.js'), server);

console.log('staged hosted bundle at', OUT);
console.log('files:', fs.readdirSync(OUT).join(', '));
